export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const inventoryConstants = {
  GETCAT_REQUEST: "GETCAT_REQUEST",
  GETCAT_SUCCESS: "GETCAT_SUCCESS",
  GETCAT_FAILURE: "GETCAT_FAILURE",

  ADDCAT_REQUEST: "ADDCAT_REQUEST",
  ADDCAT_SUCCESS: "ADDCAT_SUCCESS",
  ADDCAT_FAILURE: "ADDCAT_FAILURE",

  UPDCAT_REQUEST: "UPDCAT_REQUEST",
  UPDCAT_SUCCESS: "UPDCAT_SUCCESS",
  UPDCAT_FAILURE: "UPDCAT_FAILURE",

  DELCAT_REQUEST: "DELCAT_REQUEST",
  DELCAT_SUCCESS: "DELCAT_SUCCESS",
  DELCAT_FAILURE: "DELCAT_FAILURE",

  GETPROD_REQUEST: "GETPROD_REQUEST",
  GETPROD_SUCCESS: "GETPROD_SUCCESS",
  GETPROD_FAILURE: "GETPROD_FAILURE",

  ADDPROD_REQUEST: "ADDPROD_REQUEST",
  ADDPROD_SUCCESS: "ADDPROD_SUCCESS",
  ADDPROD_FAILURE: "ADDPROD_FAILURE",

  DELPROD_REQUEST: "DELPROD_REQUEST",
  DELPROD_SUCCESS: "DELPROD_SUCCESS",
  DELPROD_FAILURE: "DELPROD_FAILURE",

  CLEAR_STATE: "CLEAR_STATE",
};
