export const inventoryConstants = {
  GETCAT_REQUEST: "GETCAT_REQUEST",
  GETCAT_SUCCESS: "GETCAT_SUCCESS",
  GETCAT_FAILURE: "GETCAT_FAILURE",

  GETPROD_REQUEST: "GETPROD_REQUEST",
  GETPROD_SUCCESS: "GETPROD_SUCCESS",
  GETPROD_FAILURE: "GETPROD_FAILURE",

  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAILURE: "SEARCH_FAILURE",
  SEARCH_CANCEL: "SEARCH_CANCEL",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  EDITPROFILE_REQUEST: "EDITPROFILE_REQUEST",
  EDITPROFILE_SUCCESS: "EDITPROFILE_SUCCESS",
  EDITPROFILE_FAILURE: "EDITPROFILE_FAILURE",

  EDITPASS_REQUEST: "EDITPASS_REQUEST",
  EDITPASS_SUCCESS: "EDITPASS_SUCCESS",
  EDITPASS_FAILURE: "EDITPASS_FAILURE",

  RESETPASS_REQUEST: "RESETPASS_REQUEST",
  RESETPASS_SUCCESS: "RESETPASS_SUCCESS",
  RESETPASS_FAILURE: "RESETPASS_FAILURE",
};

export const cartConstants = {
  ADDTOCART_REQUEST: "ADDTOCART_REQUEST",
  ADDTOCART_SUCCESS: "ADDTOCART_SUCCESS",
  ADDTOCART_FAILURE: "ADDTOCART_FAILURE",

  GETCARTITEMS_REQUEST: "GETCARTITEMS_REQUEST",
  GETCARTITEMS_SUCCESS: "GETCARTITEMS_SUCCESS",
  GETCARTITEMS_FAILURE: "GETCARTITEMS_FAILURE",

  RESET_CART: "RESET_CART",
  RESETCART_FAILURE: "RESETCART_FAILURE",
};

export const orderConstants = {
  GETORDER_REQUEST: "GETORDER_REQUEST",
  GETORDER_SUCCESS: "GETORDER_SUCCESS",
  GETORDER_FAILURE: "GETORDER_FAILURE",

  PLACEORDER_REQUEST: "PLACEORDER_REQUEST",
  PLACEORDER_SUCCESS: "PLACEORDER_SUCCESS",
  PLACEORDER_FAILURE: "PLACEORDER_FAILURE",

  SAVEINFO_REQUEST: "SAVEINFO_REQUEST",
  SAVEINFO_SUCCESS: "SAVEINFO_SUCCESS",
  SAVEINFO_FAILURE: "SAVEINFO_FAILURE",
  CLEARORDER: "CLEARORDER",
};
